### ISSUE TITLE
RS485 half duplex serial mode -- can't transmit, only receive

### ISSUE THREAD

**Issue by thatcadguy** [FreeWaveTechnologies/ZumIQ#12]
I have Com1 and Com2 in setup mode so that I can use them from the operating system. I sent some junk over the serial ports to see if anything would happen:

```
devuser@freewave-ib:~$ cat > /dev/ttyO5
aafewafwaefawefawe
^C
devuser@freewave-ib:~$ cat > /dev/ttyO1
awefawefawefafawe
```

And the none of the lights for either com port light up on TX, as in they're not sending.

**Comment by thatcadguy** [comment]
Played around with this further -- while the lights still don't come on at all, it seems that the ports can receive data but not send. I have both ports set to RS485 half duplex, 9600 baud, no parity, 8 data bits, 1 stop bit. RS485 transceivers have to be told when to transmit/receive -- is this being handled automatically?

**Comment by javieramartine** [comment]
Same problem from here. I tried the python sample using minimalmodbus library but it's doesn't work. 

My configuration: Port com1 and com2 set to RS485 halfduplex, 9600, no parity, 8 data bits and 1 stop bits.

The z9-pe manual says that leds from Com port should blink but when i run the python script the Tx and Rx led blinks (the leds that are under the Zumlink label). 

Note:

**Comment by thatcadguy** [comment]
@javieramartine I think there's an RS485 issue they're working on, from my testing the com ports can only receive in the setup we are trying

**Comment by thatcadguy** [comment]
@javieramartine I confirmed this morning with one of their OEM application engineers that there's an issue and there will likely need to be a firmware update.
