### ISSUE TITLE
Node-Red install script

### ISSUE THREAD

**Issue by nate8199** [FreeWaveTechnologies/ZumIQ#14]
Your default install script has the part that installs node-red from npm hashed out, but it doesn't complain about it, and tries to run the service.

Maybe add a line about that in the wiki, or in the script, and mention the line that installs extra nodes(line 13).

Line 4
#sudo npm install -g --unsafe-perm node-red

**Comment by rdepew** [comment]
Thanks for the feedback. I added a note to https://github.com/FreeWaveTechnologies/ZumIQ/wiki/Linux-Environment#homedevuserbin-helper-scripts .
